apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: rl-pod-autoscaler
spec:
  template:
    spec:
      containers:
        - name: rl-pod-autoscaler
          image: rl-autoscaling:latest
          imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: busy-wait
  roleRequiresMetricsServer: true
  config:
    - name: minReplicas
      value: "1"
    - name: maxReplicas
      value: "10"
    # - name: downscaleStabilization
    #   value: "300" # seconds
    - name: interval
      value: "15000" # milliseconds
